#!/bin/bash -l
#SBATCH -D /home/grmunjal/$1/data
#SBATCH -o /home/grmunjal/$1/slurm-log/1-parsetrim-out-%j.txt
#SBATCH -e /home/grmunjal/$1/slurm-log/1-parsetrim-err-%j.txt
#SBATCH -J 1-parsetrim
#SBATCH --mem 64000
#SBATCH -c 24
#SBATCH --threads-per-core 2

set -e
set -u

#------------------------------- 
# Author: Gitanshu Munjal
# Affiliation: Brummer Lab, UC Davis 
# Date: 7/29/2016
#
# Requirements (easiest to install most of these via homebrew): 
# (1) GBS-SNP-CROP scripts (https://github.com/halelab/GBS-SNP-CROP)
# (2) USEARCH (http://www.drive5.com/usearch/download.html)
# (3) PEAR (http://sco.h-its.org/exelixis/web/software/pear/)
# (4) BWA (http://bio-bwa.sourceforge.net)
# (5) SAMtools (http://samtools.sourceforge.net)
# (6) BlastToSam.jar
# (7) Java
# (8) Blast
# (9) BEDtools
#------------------------------- 


#---------- Initialize: Set some paths and variables 

#Base directory
home=$(pwd)
base=$(pwd)/$1/data

#Keyfile
keyfile=$base/$1-key.txt

#Path to reference
refgen="/home/grmunjal/GenomeResources/RefGen/JCVI.Medtr.v4.20130313.fasta"

trimmer=$base/bin/trimmomatic-0.33.jar

#Load requirements
#module load trimmomatic/0.33
#module load usearch/7.0.1090
#module load pear/0.9.8
#module load bwa/0.7.9a
#module load samtools/1.2
#module load java/1.8
#module load blast/2.2.29
#module load bedtools/2.25
#----------#----------#----------#----------#----------#----------#----------#----------


#---------- Step 1: Parsing the raw reads (https://github.com/halelab/GBS-SNP-CROP/wiki)
cd $base

split -l 10 $keyfile key-segment-

#Changes needed here
perl $base/../code/1-SNPcalling/GBS-SNP-CROP-1.pl \
-d SE \
-b $keyfile \
-fq $1 \
-s 1 \
-e 2 \
-enz1 TGCA -enz2 CGG
#----------#----------#----------#----------#----------#----------#----------#----------

wait

#---------- Step 2: Trim based on quality and adaptors (https://github.com/halelab/GBS-SNP-CROP/wiki)
cd parsed
cp $home/ngsResources/True* ./
cp $home/bin/*jar ./

perl $base/../code/1-SNPcalling/GBS-SNP-CROP-2.pl \
-d SE \
-fq $1 \
-t 32 \
-ph 33 \
-ad TrueSeq3-SE.fa:2:30:10 \
-l 30 \
-sl 4:30 \
-tr 30 \
-m 32
#----------#----------#----------#----------#----------#----------#----------#----------

wait
