#!/bin/bash -l
#SBATCH -D /home/grmunjal/$1/data
#SBATCH -o /home/grmunjal/$1/slurm-log/2-demultiplexout-%j.txt
#SBATCH -e /home/grmunjal/$1/slurm-log/2-demultiplexerr-%j.txt
#SBATCH -J 2-demultiplex
#SBATCH --mem 64000
#SBATCH -c 24
#SBATCH --threads-per-core 2

set -e
set -u

#------------------------------- 
# Author: Gitanshu Munjal
# Affiliation: Brummer Lab, UC Davis 
# Date: 7/29/2016
#
# Requirements (easiest to install most of these via homebrew): 
# (1) GBS-SNP-CROP scripts (https://github.com/halelab/GBS-SNP-CROP)
# (2) USEARCH (http://www.drive5.com/usearch/download.html)
# (3) PEAR (http://sco.h-its.org/exelixis/web/software/pear/)
# (4) BWA (http://bio-bwa.sourceforge.net)
# (5) SAMtools (http://samtools.sourceforge.net)
# (6) BlastToSam.jar
# (7) Java
# (8) Blast
# (9) BEDtools
#------------------------------- 


#---------- Initialize: Set some paths and variables 

#Base directory
home=$(pwd)
base=$(pwd)/$1/data

#Keyfile
keyfile=$base/$1-key.txt


#Path to reference
refgen="/home/grmunjal/GenomeResources/RefGen/JCVI.Medtr.v4.20130313.fasta"

#Load requirements
#module load trimmomatic/0.33
#module load usearch/7.0.1090
#module load pear/0.9.8
#module load bwa/0.7.9a
#module load samtools/1.2
#module load java/1.8
#module load blast/2.2.29
#module load bedtools/2.25
#----------#----------#----------#----------#----------#----------#----------#----------


cd $base
cd parsed

#---------- Step 3: Demultiplex (https://github.com/halelab/GBS-SNP-CROP/wiki)
ulimit -n 1024

perl $base/../code/1-SNPcalling/GBS-SNP-CROP-3.pl \
-d SE \
-b $keyfile \
-fq $1
#----------#----------#----------#----------#----------#----------#----------#----------

