#!/bin/bash -l

#SBATCH -D /home/grmunjal/$1/data
#SBATCH -o /home/grmunjal/$1/slurm-log/segmenta-stdout-%j.txt
#SBATCH -e /home/grmunjal/$1/slurm-log/segmenta-stderr-%j.txt
#SBATCH  -J filtsega
#SBATCH -c 16


set -e
set -u

#------------------------------- 
# Author: Gitanshu Munjal
# Affiliation: Brummer Lab, UC Davis 
# Date: 7/29/2016
#
# Requirements (easiest to install most of these via homebrew): 
# (1) GBS-SNP-CROP scripts (https://github.com/halelab/GBS-SNP-CROP)
# (2) USEARCH (http://www.drive5.com/usearch/download.html)
# (3) PEAR (http://sco.h-its.org/exelixis/web/software/pear/)
# (4) BWA (http://bio-bwa.sourceforge.net)
# (5) SAMtools (http://samtools.sourceforge.net)
# (6) BlastToSam.jar
# (7) Java
# (8) Blast
# (9) BEDtools
#------------------------------- 


#---------- Initialize: Set some paths and variables 

#Base directory
#Base directory
home=$(pwd)
base=$(pwd)/$1/data

#Keyfile
keyfile=$base/$1-key.txt

cd $base/parsed/demultiplexed/
ulimit -n 8192


count=0
NR_CPUS=15

##---------- Step 7: Filter SNPs and call genotypes (https://github.com/halelab/GBS-SNP-CROP/wiki)
for filename in *segmentb*.use
do
perl $base/../code/1-SNPcalling/GBS-SNP-CROP-7.pl \
-in $filename \
-out $filename.filtered.txt \
-mnHoDepth0 11 \
-mnHoDepth1 48 \
-mnHetDepth 3 \
-altStrength 0.9 \
-mnAlleleRatio 0.1 \
-mnCall 0.75 \
-mnAvgDepth 4 \
-mxAvgDepth 200 \
&

let count+=1

[[ $((count%NR_CPUS)) -eq 0 ]] && wait

done
##----------#----------#----------#----------#----------#----------#----------#----------

wait
echo "done"

